# Generated by Django 6.0 on 2025-12-07 18:35

import django.db.models.deletion
import mixer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MixJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('output_file', models.FileField(blank=True, null=True, upload_to=mixer.models.mix_output_path)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('vs_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.vsfile')),
            ],
        ),
        migrations.CreateModel(
            name='MixTrackConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_db', models.FloatField(default=0.0)),
                ('pan', models.FloatField(default=0.0)),
                ('audio_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.audiotrack')),
                ('mix_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='mixer.mixjob')),
            ],
            options={
                'unique_together': {('mix_job', 'audio_track')},
            },
        ),
    ]
