# Generated by Django 6.0 on 2025-12-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixjob',
            name='last_downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
