# Generated by Django 6.0 on 2025-12-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixer', '0002_mixjob_last_downloaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error'), ('expired', 'Expired')], default='pending', max_length=32),
        ),
    ]
