# Generated by Django 5.2.5 on 2025-12-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiotrack',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='vsfile',
            name='original_filename',
        ),
        migrations.RemoveField(
            model_name='vsfile',
            name='stored_path',
        ),
        migrations.AddField(
            model_name='audiotrack',
            name='file',
            field=models.FileField(null=True, upload_to='audio_tracks/'),
        ),
        migrations.AddField(
            model_name='vsfile',
            name='extracted_path',
            field=models.CharField(default=None, max_length=512),
        ),
        migrations.AddField(
            model_name='vsfile',
            name='zip_file',
            field=models.FileField(null=True, upload_to='vs_files/'),
        ),
    ]
