# Generated by Django 5.2.5 on 2025-12-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_audiotrack_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsfile',
            name='extracted_path',
            field=models.CharField(default=None, max_length=512, null=True),
        ),
    ]
